service: workshop-${self:custom.name}
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:scan
          Resource: !GetAtt RestaurantsTable.Arn
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/${sls:stage}/GET/restaurants
        - Effect: Allow
          Action:
            - ssm:GetParameters
          Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssmStage, sls:stage}/get-restaurants/config
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssmStage, sls:stage}/search-restaurants/config
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssmStage, sls:stage}/search-restaurants/secret-string
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: !GetAtt EventBus.Arn
  environment:
    rest_api_url: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}    
    service_name: ${self:service}
    stage: ${sls:stage}
    ssmStage: ${param:ssmStage, sls:stage}

custom:
  name: production-ready-serverless
  export-env:
    overwrite: true

plugins:
  - serverless-export-env

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}/restaurants
      cognito_user_pool_id: !Ref CognitoUserPool
      cognito_client_id: !Ref WebCognitoUserPoolClient
      rest_api_url: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}
      cognito_server_client_id: !Ref ServerCognitoUserPoolClient
      orders_api: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}/orders
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
          authorizer: aws_iam
    environment:
      # default_results: 8
      restaurants_table: !Ref RestaurantsTable
  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    environment:
      # default_results: 8
      restaurants_table: !Ref RestaurantsTable
  place-order:
    handler: functions/place-order.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    environment:
      event_bus_name: !Ref EventBus
resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AliasAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: false
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            Name: given_name
            Mutable: true
            Required: true
            StringAttributeConstraints:
              MinLength: "1"
          - AttributeDataType: String
            Name: family_name
            Mutable: true
            Required: true
            StringAttributeConstraints:
              MinLength: "1"
          - AttributeDataType: String
            Name: email
            Mutable: true
            Required: true
            StringAttributeConstraints:
              MinLength: "1"
    WebCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: web
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED
    ServerCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: server
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED
    ParameterStoreGetRestaurantsConfig:
      Type: AWS::SSM::Parameter
      Properties:
        DataType: text
        Description: Configuration for the get-restaurants function
        Name: /${self:service}/${sls:stage}/get-restaurants/config
        Tier: Standard
        Type: String
        Value: '{"default_results":8}'
    ParameterStoreSearchRestaurantsConfig:
      Type: AWS::SSM::Parameter
      Properties:
        DataType: text
        Description: Configuration for the search-restaurants function
        Name: /${self:service}/${sls:stage}/search-restaurants/config
        Tier: Standard
        Type: String
        Value: '{"default_results":8}'
    ParameterStoreServiceUrl:
      Type: AWS::SSM::Parameter
      Properties:
        DataType: text
        Description: Service URL
        Name: /${self:service}/${sls:stage}/service-url
        Tier: Standard
        Type: String
        Value: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: !Sub ${self:custom.name}-${sls:stage}-order-events
    RestaurantNotificationTopic:
      Type: AWS::SNS::Topic
  Outputs:
    RestaurantsTableName:
      Value: !Ref RestaurantsTable
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool
    CognitoUserPoolArn:
      Value: !GetAtt CognitoUserPool.Arn
    WebClientId:
      Value: !Ref WebCognitoUserPoolClient
    ServerClientId:
      Value: !Ref ServerCognitoUserPoolClient
    ParameterStoreGetRestaurantsConfig:
      Value: !Ref ParameterStoreGetRestaurantsConfig
    ParameterStoreSearchRestaurantsConfig:
      Value: !Ref ParameterStoreSearchRestaurantsConfig
    ParameterStoreServiceUrl:
      Value: !Ref ParameterStoreServiceUrl
    EventBusName:
      Value: !Ref EventBus
    RestaurantNotificationTopicName:
      Value: !Ref RestaurantNotificationTopic